package com.example.BrighterSpace.utils;

import com.example.BrighterSpace.model.Course;
import com.example.BrighterSpace.model.Event;
import com.example.BrighterSpace.model.User;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.mail.SimpleMailMessage;
import org.springframework.mail.javamail.JavaMailSenderImpl;

import java.util.Properties;

public class MailService {

    private static final Logger logger = LoggerFactory.getLogger(MailService.class);
    private static JavaMailSenderImpl mailSender = null;

    public MailService() {
        if (mailSender == null) {
            mailSender = new JavaMailSenderImpl();
            mailSender.setHost("smtp.gmail.com");
            mailSender.setPort(587);

            mailSender.setUsername("radheypatel272@gmail.com");
            mailSender.setPassword("ynblmdhcemznnvti");
            Properties props = mailSender.getJavaMailProperties();
            props.put("mail.transport.protocol", "smtp");
            props.put("mail.smtp.auth", "true");
            props.put("mail.smtp.starttls.enable", "true");
            props.put("mail.debug", "true");
        }
    }


    public void sendRegistrationMail(String email) {
        logger.debug("Sending registration mail");
        SimpleMailMessage message = new SimpleMailMessage();
        message.setFrom("radheypatel272@gmail.com");
        message.setTo(email);
        message.setSubject("Welcome to BrighterSpace");
        message.setText("This is an autogenerated email notifying that your email has been used to register in BrighterSpace");

        mailSender.send(message);

        logger.debug("Registration mail sent successfully");
    }

    public void sendCourseRegistrationMail(Course course, User user) {
        logger.debug("Sending course registration mail");
        SimpleMailMessage message = new SimpleMailMessage();
        message.setFrom("radheypatel272@gmail.com");
        message.setTo(user.getEmail());
        message.setSubject("Course Registration");
        message.setText("This is an autogenerated email notifying that you have been enrolled to " + course.getCourseCode() + " " + course.getCourseName());

        mailSender.send(message);

        logger.debug("Course registration mail sent successfully");
    }

    public void sendEventMail(Event event, User user){
        logger.debug("Sending event creation notification mail");
        SimpleMailMessage message = new SimpleMailMessage();
        message.setFrom("radheypatel272@gmail.com");
        message.setTo(user.getEmail());
        message.setSubject("New Event for BrighterSpace users!");
        message.setText(event.getEventDescription() + "\nDate: " +event.getEventDate());

        mailSender.send(message);

        logger.debug("Event creation mail sent successfully");
    }
}
